### ISSUE TITLE
missing font files in v0.47a

### ISSUE THREAD

**Issue by McArcady** [DFgraphics/Taffer#1]
Version with tag _v0.47a_ seems broken. The font file referenced in Taffer/data/init/init.txt is missing
`[FONT:Taffer 9x - Sans-serif (straight walls).png]`

The version with tag _v0.47_ works well.

**Comment by jecowa** [comment]
Thank you, I forgot to add the new stuff. I thought that would happen automatically. I'm going to verify the other graphics packs now too.
